# Settings for the 'dev' profile, overrides application.yml

server:
  port: 8081 # Running on a different port to avoid conflicts

spring:
  # --- MariaDB Database Configuration for Development ---
  datasource:
    url: jdbc:mariadb://localhost:3306/safeworkdb_dev?createDatabaseIfNotExist=true
    username: safework_dev_user # Use a dedicated user for development
    password: ${DB_DEV_PASSWORD} # Use an environment variable for the password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      # 'update' is a good choice for development with a persistent DB.
      # It adds new tables/columns automatically, saving time.
      # Flyway will handle the initial schema creation.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true # Makes the logged SQL more readable

  # --- Enable Flyway for the persistent database ---
  flyway:
    enabled: true # Flyway must be enabled to manage the schema state

# --- Enhanced Logging for Debugging ---
logging:
  level:
    # Shows Hibernate's parameter binding in logs
    org.hibernate.type.descriptor.sql: trace