-- SafeWork API Complete Initial Schema for PostgreSQL
-- This migration creates the complete database schema including tables, indexes, and constraints
-- Designed for PostgreSQL from the ground up with JSONB support and advanced indexing

-- === CORE TABLES ===

-- Organizations table (root entity)
CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(500),
    phone VARCHAR(255),
    website VARCHAR(255),
    industry VARCHAR(255),
    size VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL,
    department_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Departments table
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    organization_id BIGINT NOT NULL,
    manager_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Locations table
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50),
    organization_id BIGINT NOT NULL,
    parent_location_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Suppliers table
CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address TEXT,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Asset Types table
CREATE TABLE asset_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL
);

-- Maintenance Schedules table
CREATE TABLE maintenance_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    frequency_value INTEGER NOT NULL,
    frequency_unit VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Assets table (main entity with JSONB for custom attributes)
CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    qr_code_id VARCHAR(255) UNIQUE,
    status VARCHAR(50) NOT NULL,
    compliance_status VARCHAR(50),
    purchase_date DATE,
    purchase_cost DECIMAL(15,2),
    warranty_expiry_date DATE,
    next_service_date DATE,
    disposal_date DATE,
    version INTEGER NOT NULL DEFAULT 0,
    custom_attributes JSONB,
    organization_id BIGINT NOT NULL,
    asset_type_id BIGINT NOT NULL,
    department_id BIGINT,
    assigned_to_user_id BIGINT,
    location_id BIGINT,
    supplier_id BIGINT,
    maintenance_schedule_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Maintenance Logs table
CREATE TABLE maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    cost DECIMAL(15,2),
    performed_date DATE NOT NULL,
    notes TEXT,
    asset_id BIGINT NOT NULL,
    performed_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Inspections table (with JSONB report data)
CREATE TABLE inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    report_data JSONB NOT NULL,
    notes TEXT,
    asset_id BIGINT NOT NULL,
    inspector_user_id BIGINT NOT NULL,
    checklist_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Issues table
CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    reported_date DATE NOT NULL,
    resolved_date DATE,
    resolution_notes TEXT,
    asset_id BIGINT NOT NULL,
    reported_by_user_id BIGINT NOT NULL,
    assigned_to_user_id BIGINT,
    resolved_by_user_id BIGINT,
    inspection_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Checklists table (with JSONB template data)
CREATE TABLE checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    template_data JSONB NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- === UNIQUE CONSTRAINTS ===

-- Add unique constraint for asset organization scope
ALTER TABLE assets ADD CONSTRAINT uk_assets_org_qr UNIQUE (organization_id, qr_code_id);

-- Add unique constraint for organization-scoped entities
ALTER TABLE asset_types ADD CONSTRAINT uk_asset_types_org_name UNIQUE (organization_id, name);
ALTER TABLE departments ADD CONSTRAINT uk_departments_org_name UNIQUE (organization_id, name);
ALTER TABLE locations ADD CONSTRAINT uk_locations_org_name UNIQUE (organization_id, name);
ALTER TABLE suppliers ADD CONSTRAINT uk_suppliers_org_name UNIQUE (organization_id, name);
ALTER TABLE checklists ADD CONSTRAINT uk_checklists_org_name UNIQUE (organization_id, name);

-- === PERFORMANCE INDEXES ===

-- JSONB GIN Indexes for Advanced Querying
CREATE INDEX idx_assets_custom_attributes_gin ON assets USING GIN (custom_attributes);
CREATE INDEX idx_inspections_report_data_gin ON inspections USING GIN (report_data);
CREATE INDEX idx_checklists_template_data_gin ON checklists USING GIN (template_data);

-- Multi-Tenant Organization Indexes
CREATE INDEX idx_assets_organization_id ON assets (organization_id);
CREATE INDEX idx_users_organization_id ON users (organization_id);
CREATE INDEX idx_departments_organization_id ON departments (organization_id);
CREATE INDEX idx_locations_organization_id ON locations (organization_id);
CREATE INDEX idx_suppliers_organization_id ON suppliers (organization_id);
CREATE INDEX idx_asset_types_organization_id ON asset_types (organization_id);
CREATE INDEX idx_maintenance_schedules_organization_id ON maintenance_schedules (organization_id);
CREATE INDEX idx_checklists_organization_id ON checklists (organization_id);

-- Foreign Key Relationship Indexes
CREATE INDEX idx_assets_asset_type_id ON assets (asset_type_id);
CREATE INDEX idx_assets_department_id ON assets (department_id);
CREATE INDEX idx_assets_assigned_to_user_id ON assets (assigned_to_user_id);
CREATE INDEX idx_assets_location_id ON assets (location_id);
CREATE INDEX idx_assets_supplier_id ON assets (supplier_id);
CREATE INDEX idx_assets_maintenance_schedule_id ON assets (maintenance_schedule_id);

-- User and department relationships
CREATE INDEX idx_users_department_id ON users (department_id);
CREATE INDEX idx_departments_manager_id ON departments (manager_id);

-- Location hierarchy
CREATE INDEX idx_locations_parent_location_id ON locations (parent_location_id);

-- Maintenance and inspection relationships
CREATE INDEX idx_maintenance_logs_asset_id ON maintenance_logs (asset_id);
CREATE INDEX idx_maintenance_logs_performed_by_user_id ON maintenance_logs (performed_by_user_id);
CREATE INDEX idx_inspections_asset_id ON inspections (asset_id);
CREATE INDEX idx_inspections_inspector_user_id ON inspections (inspector_user_id);
CREATE INDEX idx_inspections_checklist_id ON inspections (checklist_id);

-- Issue tracking relationships
CREATE INDEX idx_issues_asset_id ON issues (asset_id);
CREATE INDEX idx_issues_reported_by_user_id ON issues (reported_by_user_id);
CREATE INDEX idx_issues_assigned_to_user_id ON issues (assigned_to_user_id);
CREATE INDEX idx_issues_resolved_by_user_id ON issues (resolved_by_user_id);
CREATE INDEX idx_issues_inspection_id ON issues (inspection_id);

-- Performance Indexes for Common Queries
CREATE INDEX idx_assets_status ON assets (status);
CREATE INDEX idx_assets_compliance_status ON assets (compliance_status);
CREATE INDEX idx_assets_next_service_date ON assets (next_service_date);
CREATE INDEX idx_assets_warranty_expiry_date ON assets (warranty_expiry_date);
CREATE INDEX idx_users_email ON users (email);

-- Composite Indexes for Complex Queries
CREATE INDEX idx_assets_org_status ON assets (organization_id, status);
CREATE INDEX idx_assets_org_next_service ON assets (organization_id, next_service_date)
    WHERE next_service_date IS NOT NULL;
CREATE INDEX idx_users_org_role ON users (organization_id, role);

-- Partial Indexes for Specific Conditions
CREATE INDEX idx_assets_active ON assets (organization_id, status, asset_type_id)
    WHERE status != 'DISPOSED';

-- === FOREIGN KEY CONSTRAINTS ===

-- Core Organization Relationships
ALTER TABLE users 
    ADD CONSTRAINT fk_users_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE users 
    ADD CONSTRAINT fk_users_department 
    FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;

-- Organizational Structure Constraints
ALTER TABLE departments 
    ADD CONSTRAINT fk_departments_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE departments 
    ADD CONSTRAINT fk_departments_manager 
    FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE locations 
    ADD CONSTRAINT fk_locations_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE locations 
    ADD CONSTRAINT fk_locations_parent 
    FOREIGN KEY (parent_location_id) REFERENCES locations (id) ON DELETE SET NULL;

ALTER TABLE suppliers 
    ADD CONSTRAINT fk_suppliers_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE asset_types 
    ADD CONSTRAINT fk_asset_types_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE maintenance_schedules 
    ADD CONSTRAINT fk_maintenance_schedules_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

-- Asset Management Constraints
ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_asset_type 
    FOREIGN KEY (asset_type_id) REFERENCES asset_types (id) ON DELETE RESTRICT;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_department 
    FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE SET NULL;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_assigned_user 
    FOREIGN KEY (assigned_to_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_location 
    FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE SET NULL;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_supplier 
    FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE SET NULL;

ALTER TABLE assets 
    ADD CONSTRAINT fk_assets_maintenance_schedule 
    FOREIGN KEY (maintenance_schedule_id) REFERENCES maintenance_schedules (id) ON DELETE SET NULL;

-- Maintenance and Inspection Constraints
ALTER TABLE maintenance_logs 
    ADD CONSTRAINT fk_maintenance_logs_asset 
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE;

ALTER TABLE maintenance_logs 
    ADD CONSTRAINT fk_maintenance_logs_performed_by 
    FOREIGN KEY (performed_by_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE inspections 
    ADD CONSTRAINT fk_inspections_asset 
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE;

ALTER TABLE inspections 
    ADD CONSTRAINT fk_inspections_inspector 
    FOREIGN KEY (inspector_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE inspections 
    ADD CONSTRAINT fk_inspections_checklist 
    FOREIGN KEY (checklist_id) REFERENCES checklists (id) ON DELETE SET NULL;

-- Issue Tracking Constraints
ALTER TABLE issues 
    ADD CONSTRAINT fk_issues_asset 
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE;

ALTER TABLE issues 
    ADD CONSTRAINT fk_issues_reported_by 
    FOREIGN KEY (reported_by_user_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE issues 
    ADD CONSTRAINT fk_issues_assigned_to 
    FOREIGN KEY (assigned_to_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE issues 
    ADD CONSTRAINT fk_issues_resolved_by 
    FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE issues 
    ADD CONSTRAINT fk_issues_inspection 
    FOREIGN KEY (inspection_id) REFERENCES inspections (id) ON DELETE SET NULL;

-- Checklist Constraints
ALTER TABLE checklists 
    ADD CONSTRAINT fk_checklists_organization 
    FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;

-- === DATA INTEGRITY CHECK CONSTRAINTS ===

-- Ensure positive values for costs and frequencies
ALTER TABLE assets 
    ADD CONSTRAINT chk_assets_purchase_cost_positive 
    CHECK (purchase_cost IS NULL OR purchase_cost >= 0);

ALTER TABLE maintenance_logs 
    ADD CONSTRAINT chk_maintenance_logs_cost_positive 
    CHECK (cost IS NULL OR cost >= 0);

ALTER TABLE maintenance_schedules 
    ADD CONSTRAINT chk_maintenance_schedules_frequency_positive 
    CHECK (frequency_value > 0);

-- Ensure logical date ordering
ALTER TABLE assets 
    ADD CONSTRAINT chk_assets_warranty_after_purchase 
    CHECK (warranty_expiry_date IS NULL OR purchase_date IS NULL OR warranty_expiry_date >= purchase_date);

ALTER TABLE issues 
    ADD CONSTRAINT chk_issues_resolved_after_reported 
    CHECK (resolved_date IS NULL OR resolved_date >= reported_date);

-- Ensure valid enum-like values (as additional safety for application enums)
ALTER TABLE assets 
    ADD CONSTRAINT chk_assets_status_valid 
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DISPOSED'));

ALTER TABLE assets 
    ADD CONSTRAINT chk_assets_compliance_status_valid 
    CHECK (compliance_status IS NULL OR compliance_status IN ('COMPLIANT', 'NON_COMPLIANT', 'PENDING', 'UNKNOWN'));

ALTER TABLE issues 
    ADD CONSTRAINT chk_issues_status_valid 
    CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'));

ALTER TABLE issues 
    ADD CONSTRAINT chk_issues_priority_valid 
    CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'));

-- === COLUMN COMMENTS FOR DOCUMENTATION ===

COMMENT ON COLUMN assets.custom_attributes IS 'JSONB column for flexible asset attributes and metadata';
COMMENT ON COLUMN inspections.report_data IS 'JSONB column for structured inspection reports and findings';
COMMENT ON COLUMN checklists.template_data IS 'JSONB column for dynamic checklist templates and configurations';

-- === SCHEMA READY ===
-- This completes the initial PostgreSQL schema for SafeWork API
-- All tables, indexes, constraints, and data integrity rules are in place