-- SafeWork API Initial Schema for PostgreSQL
-- This migration creates the base schema structure

-- Organizations table (root entity)
CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(500),
    phone VARCHAR(255),
    website VARCHAR(255),
    industry VARCHAR(255),
    size VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL,
    department_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Departments table
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    organization_id BIGINT NOT NULL,
    manager_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Locations table
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50),
    organization_id BIGINT NOT NULL,
    parent_location_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Suppliers table
CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    address TEXT,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Asset Types table
CREATE TABLE asset_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    organization_id BIGINT NOT NULL
);

-- Maintenance Schedules table
CREATE TABLE maintenance_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    frequency_value INTEGER NOT NULL,
    frequency_unit VARCHAR(50) NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Assets table (main entity with basic JSON column)
CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    qr_code_id VARCHAR(255) UNIQUE,
    status VARCHAR(50) NOT NULL,
    compliance_status VARCHAR(50),
    purchase_date DATE,
    purchase_cost DECIMAL(15,2),
    warranty_expiry_date DATE,
    next_service_date DATE,
    disposal_date DATE,
    version INTEGER NOT NULL DEFAULT 0,
    custom_attributes JSON,
    organization_id BIGINT NOT NULL,
    asset_type_id BIGINT NOT NULL,
    department_id BIGINT,
    assigned_to_user_id BIGINT,
    location_id BIGINT,
    supplier_id BIGINT,
    maintenance_schedule_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Maintenance Logs table
CREATE TABLE maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    cost DECIMAL(15,2),
    performed_date DATE NOT NULL,
    notes TEXT,
    asset_id BIGINT NOT NULL,
    performed_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Inspections table (with JSON report data)
CREATE TABLE inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    report_data JSON NOT NULL,
    notes TEXT,
    asset_id BIGINT NOT NULL,
    inspector_user_id BIGINT NOT NULL,
    checklist_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Issues table
CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    reported_date DATE NOT NULL,
    resolved_date DATE,
    resolution_notes TEXT,
    asset_id BIGINT NOT NULL,
    reported_by_user_id BIGINT NOT NULL,
    assigned_to_user_id BIGINT,
    resolved_by_user_id BIGINT,
    inspection_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Checklists table (with JSON template data)
CREATE TABLE checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    template_data JSON NOT NULL,
    organization_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Add unique constraint for asset organization scope
ALTER TABLE assets ADD CONSTRAINT uk_assets_org_qr UNIQUE (organization_id, qr_code_id);

-- Add unique constraint for organization-scoped entities
ALTER TABLE asset_types ADD CONSTRAINT uk_asset_types_org_name UNIQUE (organization_id, name);
ALTER TABLE departments ADD CONSTRAINT uk_departments_org_name UNIQUE (organization_id, name);
ALTER TABLE locations ADD CONSTRAINT uk_locations_org_name UNIQUE (organization_id, name);
ALTER TABLE suppliers ADD CONSTRAINT uk_suppliers_org_name UNIQUE (organization_id, name);
ALTER TABLE checklists ADD CONSTRAINT uk_checklists_org_name UNIQUE (organization_id, name);